IDIR =../include
CC=gcc
CFLAGS=-ggdb -I$(IDIR) -Wall

ODIR=obj
LDIR=lib
BDIR=bin

LIBS=-lm

_DEPS = #server.h
DEPS = $(patsubst %,$(IDIR)/%,$(_DEPS))

_OBJ = server.o
OBJ = $(patsubst %,$(ODIR)/%,$(_OBJ))


$(ODIR)/%.o: src/%.c $(DEPS)
	
	mkdir -p $(ODIR) $(BDIR)
	$(CC) -c -o $@ $< $(CFLAGS)

server: $(OBJ)
	mkdir -p $(ODIR) $(BDIR)
	$(CC) -o $(BDIR)/$@ $^ $(CFLAGS) $(LIBS)

.PHONY: clean

clean:
	rm -f server $(ODIR)/*.o *~ core $(INCDIR)/*~ 
